# Generated by Django 4.1.3 on 2022-12-02 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_profile_photo_vendor_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='admin',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.customer'),
        ),
        migrations.AddField(
            model_name='post',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.vendor'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
