# Generated by Django 4.1.3 on 2022-12-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_cart_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.BooleanField(default=False),
        ),
    ]
