# Generated by Django 4.1.3 on 2022-12-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_vendor_admin_orderitem_customer_post_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
