# Generated by Django 4.1.3 on 2022-12-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_vendor_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='approval',
        ),
    ]
