# Generated by Django 4.1.3 on 2022-12-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_remove_vendor_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='rider',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
