# Generated by Django 4.1.3 on 2022-12-06 09:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_remove_cart_created_at_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dkcivjz16/image/upload/v1670318972/moto%20foods/rowan-freeman-clYlmCaQbzY-unsplash_saxitz.jpg', max_length=255, verbose_name='photo'),
        ),
    ]
